trigger:
  - feature/auth

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-credentials

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: $(knownHosts)
        sshPublicKey: $(publicKey)
        sshKeySecureFile: 'id_rsa'
  - script: |
      docker --version
      echo $(username)
      echo $(password)
      java --version
      mvn --version
    displayName: 'Checking environment'
  - script: |
      mvn clean test-compile
    displayName: 'Compile project'
  - script: |
      mvn test -pl formservice
    displayName: 'Running tests'
  - script: |
      mvn package -DskipTests -pl formservice
    displayName: 'Package application'
  - script: |
      mvn package -pl eventservice
      docker-compose up -d
      mvn test -X -pl googleformintegrationtest
      docker logs $(docker container ls --all | grep formservice | awk '{print $1}')
    displayName: 'Run integration tests'
  - script: |
      docker images
    displayName: 'Check images'
  - script: |
      git config --global user.email "azure_dummy@example.com"
      git config --global user.name "Azure Dummy"
      tag=$(git rev-parse --short HEAD)
      echo $tag
      git tag -a $tag -m "my version ${tag}"
      git push origin $tag