trigger:
  - feature/auth

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: docker-credentials

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - script: |
      docker --version
      echo $(username)
      echo $(password)
      java --version
      mvn --version
    displayName: 'Checking environment'
  - script: |
      mvn clean compile
    displayName: 'Compile project'
  - script: |
      mvn test -pl formservice
    displayName: 'Running tests'
  - script: |
      mvn package -DskipTests -pl formservice
    displayName: 'Package application'
  - script: |
      docker-compose up -d
    displayName: 'Create docker images'
  - script: |
      docker images
    displayName: 'Check images'