trigger:
  - feature/auth

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: demo-variable-group

steps:
  - script: |
      docker --version
    displayName: 'Checking Docker Version'
#  - script: |
#      terraform --version
#    displayName: 'Checking Terraform Version'
#  - script: |
#      java --version
#    displayName: 'Checking Java Version'
#  - script: |
#      echo $(demo-var1)
#      echo $(demo-var2)
#    displayName: 'Print Values from a Variable Group'
#  - task: Gradle@2
#    inputs:
#      gradleWrapperFile: './gradlew'
#      jdkVersionOption: '1.11'
#      tasks: 'clean compileTestJava'
#    displayName: 'Compile Project'
#  - task: Gradle@2
#    inputs:
#      gradleWrapperFile: './gradlew'
#      jdkVersionOption: '1.11'
#      tasks: 'test'
#    displayName: 'Run Unit Tests'
#  - script: |
#      ./gradlew build -x test
#    displayName: 'Create the JAR file'