apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azuresecretproviderclass
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: env-credentials
      type: Opaque
      data:
        - objectName: googleform-db-password
          key: secret-key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secret.UserAssignedIdentityId }}
    keyvaultName: "codehunterskeyvault"
    objects:  |
      array:
        - |
          objectName: googleform-db-password
          objectType: secret
    tenantId: "f12402fb-94c0-40db-8a18-6dca573c3b66"