googleform:
  url-generation:
    batch-size: 10
    fixed-rate-ms: 600000
  event-service:
    host: http://eventservice
    port: 8080


spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@mongodb:27017/formdatabase?authSource=admin
      #authentication-database: admin
      #username: mongoadmin
      #password: secret
      #database: formdatabase
      #port: 27017
      #host: mongodb