googleform:
  url-generation:
    batch-size: 10
    fixed-rate-ms: 600000

spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@mongo:27017/formdatabase?authSource=admin
      database: formdatabase