googleform:
  url-generation:
    batch-size: 10
    fixed-rate-ms: 600000

spring:
  data:
    mongodb:
      #uri: mongodb://mongoadmin:secret@mongoservice:27017/formdatabase?authSource=admin
      database: formdatabase
      host: mongo
      port: 27017
      authentication-database: admin
      username: mongoadmin
      password: secret
