deployment:
  name: googleform
  version: todo
service:
  name: googleformservice
secret:
  UserAssignedIdentityId: 7baad0cd-6743-417d-a364-2755c687b841
autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 15